import { Noto_Sans_KR } from "next/font/google";

import "./globals.css";
import Provider from "@/components/Provider";

const noto = Noto_Sans_KR({
  subsets: ["latin"], // 또는 preload: false
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="kr">
      <Provider>
        <body className={noto.className}>{children}</body>
      </Provider>
    </html>
  );
}
